<?php
require_once '../lib/Repository.php';
/**
 * Datenbankschnittstelle für die Benutzer
 */
  class LoginRepository extends Repository
  {
    public function readAll()
    {
        return parent::readAll(); // TODO: Change the autogenerated stub
    }
  }

?>